/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_springbootdemo_Bsdiff */

#ifndef _Included_org_example_springbootdemo_Bsdiff
#define _Included_org_example_springbootdemo_Bsdiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_springbootdemo_Bsdiff
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_springbootdemo_Bsdiff_bsdiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_example_springbootdemo_Bsdiff
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_springbootdemo_Bsdiff_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
